#!/bin/bash

# StreamGuard RTMP Server Setup Script
# This script sets up the RTMP server using Docker and SRS (Simple Realtime Server)

echo "🚀 StreamGuard RTMP Server Setup"
echo "================================="

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    echo "   Visit: https://docs.docker.com/get-docker/"
    exit 1
fi

echo "✅ Docker found"

# Check if port 1935 is available
if lsof -Pi :1935 -sTCP:LISTEN -t >/dev/null ; then
    echo "⚠️  Port 1935 is already in use. Stopping existing service..."
    docker stop streamguard-rtmp 2>/dev/null || true
    sleep 2
fi

echo "✅ Port 1935 is available"

# Check if .env file exists
if [ ! -f .env ]; then
    echo "📝 Creating .env file..."
    cat > .env << EOF
# StreamGuard Environment Variables
VITE_WALRUS_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space
VITE_WALRUS_AGGREGATOR_URL=https://aggregator.walrus-testnet.walrus.space
VITE_SUI_NETWORK=testnet
VITE_PACKAGE_ID=0x5ddfb36c0f29f30aabfe4bf50dcf02707411223a06415743f181074df58b4974
EOF
    echo "✅ .env file created"
else
    echo "✅ .env file already exists"
fi

echo "🚀 Starting RTMP server..."
echo "   This will run SRS (Simple Realtime Server) on ports:"
echo "   - 1935 (RTMP)"
echo "   - 8080 (HTTP)"
echo "   - 1985 (API)"

# Start the RTMP server with all necessary ports
docker run --rm -d \
    --name streamguard-rtmp \
    -p 1935:1935 \
    -p 8080:8080 \
    -p 1985:1985 \
    ossrs/srs:5

# Wait a moment for the server to start
sleep 3

# Check if the server is running
if docker ps | grep -q streamguard-rtmp; then
    echo "✅ RTMP server started!"
    echo ""
    echo "📋 Configuration for OBS Studio:"
    echo "   Server: rtmp://localhost:1935/live"
    echo "   Stream Key: [Use the key generated by StreamGuard]"
    echo ""
    echo "🌐 You can monitor streams at: http://localhost:8080"
    echo "🔧 API endpoint available at: http://localhost:1985/api/v1"
    echo ""
    echo "⏹️  To stop the server, press Ctrl+C or run:"
    echo "   docker stop streamguard-rtmp"
    echo ""
    echo "🎬 Now you can create a stream in StreamGuard and start streaming!"
else
    echo "❌ Failed to start RTMP server"
    exit 1
fi 